### ISSUE TITLE
Can the CDN layer itself be abstracted and be just one of 100's of community developed transport plugins?

### ISSUE THREAD

**Issue by freakynit** [doxx/darkflare#1]
Hi, so I had similar idea for long, but not the technical know-how.

I was thinking what else could be used instead of just CDN? Can this part, the transport part, be abstracted out, and replaced with installable plugins that community can build. A few example of possible(probable?) transports:

1. Blockchain networks
2. Decentralized storage layers like ipfs
3. Decentralized social networks/protocols like mastodon/bluesky/at-protocol by encoding packets as contents
4. Email
5. MQTT
6. Local long range protocols(with routing component to act like bgp) like wifi, bluetooth, custom protocol
7. Proxying through gaming servers by encoding packets as in-game data
8. Proxying packets as messages over instant messaging apps like whatsapp, telegram, line, snapchat, etc.
9. P2P protocols like bittorrent

There can be 100's more..

This, then, would be truly unstoppable.

**Comment by doxx** [comment]
This is an experiment for TCP over CDN. I have done others for TCP over DNS for example. Each one has their own unique issue but it's pretty fun.
