### ISSUE TITLE
SSH Connection Issues with -allow-direct: Bad packet length errors

### ISSUE THREAD

**Issue by kakahu2015** [doxx/darkflare#12]
Title: Frequent "Bad packet length" errors when using -allow-direct flag

Description:
When enabling `-allow-direct` flag on the server side, most SSH client connections fail with "Bad packet length" errors. The normal "Permission denied" for missing keys is expected, but the packet length errors appear to be a separate issue.

## Current Behavior
- Most connection attempts fail with error: `Bad packet length 1397966893`
- Getting occasional expected "Permission denied" errors due to missing SSH keys
- Connection success rate is extremely low, with most attempts failing due to packet length errors

## Steps to Reproduce
1. Start darkflare-server with `-allow-direct` flag enabled
2. Try to connect using SSH: `ssh -p 2222 root@127.0.0.1`
3. Connection mostly fails with packet length errors, occasionally shows expected auth errors

## Error Logs
Primary error (the issue):
Bad packet length 1397966893.
ssh_dispatch_run_fatal: Connection to 127.0.0.1 port 2222: message authentication code incorrect

## Additional Notes
The packet length errors appear to be a connection/protocol issue rather than an authentication issue, as they occur before reaching the authentication stage.

**Comment by doxx** [comment]
I updated the code and the release. Can you try again? There were some major server changes recently. Also, this can happen if the destination host doesn't resolve. I added more error handling for that as well. You can also test against the new open relay https://cdn.miami.us.doxx.net:443 to see if you have better results.
