### ISSUE TITLE
How to identify and separate data sent to the server?

### ISSUE THREAD

**Issue by MrParAziT** [doxx/darkflare#13]
Hey champ
First of all thanks for your updates...

In previous version i was using origin rules to forward data from darkflare with set user-agent DarkFlare/1.0 (as you know i have website on my 443 port) but i know that isn't good solution for multi user-agent (maybe in future you will add some feature like random user-agent), so do you have any idea for this?? (other than haproxy)

Much appreciated in advance for your answer.

**Comment by doxx** [comment]
Ahhh okay. You can edit the server/main.go file to change the user-agent if you want. Just run make after and you should get what you need.

**Comment by doxx** [comment]
I wanted it to be more stealthy

**Comment by doxx** [comment]
Ohhh, there is a special X-For header that's now used for the client/server that isn't part of the usual stuff in the header. You can filter on that with a rule.
