### ISSUE TITLE
Darkflare-server did't support 0.0.0.0 and localhost

### ISSUE THREAD

**Issue by MrParAziT** [doxx/darkflare#14]
./darkflare-server -o https://0.0.0.0:8080 -c /root/darkflare/cert.pem -k /root/darkflare/key.pem
2024/12/03 14:13:10 Origin host must be a local IP address
./darkflare-server -o https://localhost:8080 -c /root/darkflare/cert.pem -k /root/darkflare/key.pem
2024/12/03 14:18:08 Origin host must be a local IP address

why bro? 0.0.0.0 and localhost are equal to 127.0.0.1

**Comment by doxx** [comment]
Looks like a bug. I’ll take a look shortly.

**Comment by doxx** [comment]
Binding localhost has been fixed. Pushing a new release now. It's now current in HEAD.
