### ISSUE TITLE
protocol error: received DATA after END_STREAM

### ISSUE THREAD

**Issue by MrParAziT** [doxx/darkflare#16]
i don't why but i got this error **protocol error: received DATA after END_STREAM** in client side

**Comment by doxx** [comment]
It's due to the HTTP/2 handling with the CDN. I think they end the stream but have some session hanging. I don't think it's causing an issue. I might hide those messages.

**Comment by doxx** [comment]
I'm live on discord if you need to chat about things: https://discord.gg/7wVKeP88
