### ISSUE TITLE
Low speed after new version(1.2)

### ISSUE THREAD

**Issue by MrParAziT** [doxx/darkflare#17]
Before, i had 30mbps download and 2mbps upload (avg) but now both of them never up 4mbps, maybe is it from buffer size??

Umm...  It is possible because i live in iran? cause in here we have badly firewall

**Comment by doxx** [comment]
I'll take a look. I've been testing and getting 20Mbps down and >50Mbps up. Maybe it's your testing server? Also, how is it working for you? Are you able to get past blocks with this?

**Comment by doxx** [comment]
Join my discord server and I can chat more about the config and we can figure it out. https://discord.com/channels/1313170561303576666/1313170561303576669

**Comment by doxx** [comment]
Okay I think I fixed it. It's pretty fast now.
