### ISSUE TITLE
Clarification on Cloudflare to Origin Server Communication

### ISSUE THREAD

**Issue by sinnet3000** [doxx/darkflare#5]
Hello,

I am seeking clarification on the communication between Cloudflare and the Origin Server (Darkflare). Based on my understanding of the current implementation, it seems that the code supports only HTTP communication between Cloudflare and the Origin Server. Is this correct?

If so, I suggest the following updates:
	1.	**Diagram Update**:
The diagram in the README.md could be updated to explicitly reflect that the communication is currently HTTP-only. This would help avoid any confusion.
	2.	**Future Plans Mention:**
If there are plans to support HTTPS communication between Cloudflare and the Origin Server, it might be helpful to note this in the documentation as a planned enhancement or roadmap item.

Please let me know if my understanding is correct or if I am missing something.

Thank you for your hard work and for starting this project!

**Comment by doxx** [comment]
Hey Luis… It’s all HTTPs.

**Comment by doxx** [comment]
I added support for http and https and any port today.

**Comment by doxx** [comment]
Okay full https TLS support for the origin server has been added. Please review the updated documents.
