### ISSUE TITLE
 SSL handshake failed Error code 525

### ISSUE THREAD

**Issue by MrParAziT** [doxx/darkflare#6]
I got this error in cloudflare, what should i do?

**Comment by doxx** [comment]
Make sure your target -t is https:// on the client. Make sure your target DNS entry points to Cloudflare not your origin host.

**Comment by MrCapsLock** [comment]
Hi, I can confirm with automatic ssl option in cf and simple configuration based on README file, I'm facing 525 too. I think client can't provide secure connection between cf and itself.
client: ./bin/darkflare-client-linux-amd64 -l 8080 -t https://my.cf.domain -debug
server: ./bin/darkflare-server-linux-amd64 -d x.x.x.x:p -p 443

Should I change anything in cf settings?
@doxx
