### ISSUE TITLE
Got connection: reused=true

### ISSUE THREAD

**Issue by senggai** [doxx/darkflare#7]
[DEBUG] Making GET request to: https://cf.----.top:443/t.php (Host: cf.----.top:443)
2024/11/27 23:54:42.323076 main.go:93: [DEBUG] Getting connection for cf.----.top:443
2024/11/27 23:54:42.323076 main.go:93: [DEBUG] Got connection: reused=true, was_idle=true, idle_time=1.0004109s, local=192.168.0.103:64556, remote=172.67.164.86:443
2024/11/27 23:54:42.415332 main.go:93: [DEBUG] Server returned non-200 status. Body: ���V,tCrN˸���'L��w��0�A���mOY6���<w�U�X���r�Y>�/Ca�Nt��X����\YvE�����<������a�$�;�

**Comment by doxx** [comment]
I'll take a look at that. Do you have the server side -debug output as well? Looks like something got handled incorrectly.

**Comment by senggai** [comment]
> I'll take a look at that. Do you have the server side -debug output as well? Looks like something got handled incorrectly.

root@test2:~# ./darkflare-server -d localhost:22 -p 8080 -debug
2024/11/27 10:45:34 DarkFlare server running on port 8080
2024/11/27 10:45:34 Forwarding to localhost:22
2024/11/27 10:45:49 Received GET request from 




root@test2:~# ss -tulnp
Netid    State     Recv-Q     Send-Q         Local Address:Port          Peer Address:Port    Process                                                                                       
udp      UNCONN    0          0                          *:23882                    *:*        users:(("sing-box",pid=502,fd=7))                                                            
tcp      LISTEN    0          128                  0.0.0.0:22                 0.0.0.0:*        users:(("sshd",pid=514,fd=3))                                                                
tcp      LISTEN    0          128                127.0.0.1:6010               0.0.0.0:*        users:(("sshd",pid=521,fd=10))                                                               
tcp      LISTEN    0          128                127.0.0.1:6011               0.0.0.0:*        users:(("sshd",pid=733,fd=10))                                                               
tcp      LISTEN    0          511                  0.0.0.0:80                 0.0.0.0:*        users:(("nginx",pid=511,fd=6),("nginx",pid=509,fd=6))                                        
tcp      LISTEN    0          128                     [::]:22                    [::]:*        users:(("sshd",pid=514,fd=4))                                                                
tcp      LISTEN    0          128                    [::1]:6010                  [::]:*        users:(("sshd",pid=521,fd=9))                                                                
tcp      LISTEN    0          128                    [::1]:6011                  [::]:*        users:(("sshd",pid=733,fd=9))                                                                
tcp      LISTEN    0          4096                       *:8080                     *:*        users:(("darkflare-serve",pid=668,fd=3))     


thanks

**Comment by senggai** [comment]
when i  test a new server 
the client return 
<title>cf-512.testnew.top | 521: Web server is down</title>

there is a cloudflare page

**Comment by doxx** [comment]
The first thing that comes to mind is that maybe Cloudlfare is sending you an error message. I'll see if I can add some error handling for that. What happens if you try to curl to the cloudflare hosted URL directly? I'd debug that first. Leave the server side running and do a curl https://cf.----.top:443 and see if the output is what you expect.

**Comment by doxx** [comment]
Yeah so maybe Cloudflare can't reach your origin server. You need to define some origin Rule to make sure they know to hit port 8080 and not a default port like 80 or 443.

**Comment by senggai** [comment]
> Yeah so maybe Cloudflare can't reach your origin server. You need to define some origin Rule to make sure they know to hit port 8080 and not a default port like 80 or 443.

ok i will try that , thanks

**Comment by doxx** [comment]
I'll make a note of adding better passthrough of the cloudflare errors today. I also need to add https support for the origin server along with this TLS spoofing.

**Comment by doxx** [comment]
I updated the -debug output for the client to include CDN error messages. I'll push a release but you can download HEAD and get them. See if that helps you with debugging. Also make sure all of the DNS is correct:  

dig cf.testnew.top to make sure it's pointing to the CDN... Also make sure the CDN has the right host to the origin server.

**Comment by senggai** [comment]
> I updated the -debug output for the client to include CDN error messages. I'll push a release but you can download HEAD and get them. See if that helps you with debugging. Also make sure all of the DNS is correct:
> 
> dig cf.testnew.top to make sure it's pointing to the CDN... Also make sure the CDN has the right host to the origin server.

ok i will test

**Comment by senggai** [comment]
> I updated the -debug output for the client to include CDN error messages. I'll push a release but you can download HEAD and get them. See if that helps you with debugging. Also make sure all of the DNS is correct:
> 
> dig cf.testnew.top to make sure it's pointing to the CDN... Also make sure the CDN has the right host to the origin server.

i had update all the files and run a new test but it not work success

client log here 

2024/11/28 01:37:41.160805 main.go:114: [DEBUG] New connection established - Local: 127.0.0.1:2222, Remote: 127.0.0.1:61452
2024/11/28 01:37:41.160805 main.go:114: [DEBUG] Making GET request to: https://cf-512.testnew.top/g3ef7pm00.ini (Host: cf-512.testnew.top)
2024/11/28 01:37:41.160805 main.go:114: [DEBUG] Read 3 bytes from local connection
2024/11/28 01:37:41.160805 main.go:114: [DEBUG] Making POST request to: https://cf-512.testnew.top/vd2z6cm2.cfg (Host: cf-512.testnew.top)
2024/11/28 01:37:41.274588 main.go:114: [DEBUG] POST request completed in 879.1555ms, status: 200 OK
2024/11/28 01:37:41.355344 main.go:114: [DEBUG] Making POST request to: https://cf-512.testnew.top/4da.jpg (Host: cf-512.testnew.top)
2024/11/28 01:37:41.355515 main.go:114: [DEBUG] Connection handler completed for 127.0.0.1:61446
2024/11/28 01:37:41.376024 main.go:114: [DEBUG] POST request completed in 826.0391ms, status: 200 OK
2024/11/28 01:37:41.401057 main.go:114: [DEBUG] Making POST request to: https://cf-512.testnew.top/l1tg8unpe.jsp (Host: cf-512.testnew.top)
2024/11/28 01:37:41.401057 main.go:114: [DEBUG] Connection handler completed for 127.0.0.1:61449
2024/11/28 01:37:41.405840 main.go:114: [DEBUG] Polling stopped for 127.0.0.1:61446
2024/11/28 01:37:41.451754 main.go:114: [DEBUG] Polling stopped for 127.0.0.1:61449
2024/11/28 01:37:41.724792 main.go:114: [DEBUG] Connection cleanup completed for 127.0.0.1:61446
2024/11/28 01:37:41.766690 main.go:114: [DEBUG] Connection cleanup completed for 127.0.0.1:61449
2024/11/28 01:37:41.963923 main.go:114: [DEBUG] POST request completed in 803.1184ms, status: 200 OK
2024/11/28 01:37:42.083577 main.go:114: [DEBUG] Making POST request to: https://cf-512.testnew.top/t9c3.ico (Host: cf-512.testnew.top)
2024/11/28 01:37:42.083577 main.go:114: [DEBUG] Connection handler completed for 127.0.0.1:61452
2024/11/28 01:37:42.134603 main.go:114: [DEBUG] Polling stopped for 127.0.0.1:61452
2024/11/28 01:37:42.484198 main.go:114: [DEBUG] Connection cleanup completed for 127.0.0.1:61452


server log

2024/11/27 12:38:12 GET: Read 68 bytes from connection for session 76429d82
2024/11/27 12:38:12 Response: Sending 68 bytes (encoded: 136 bytes) for session 76429d82 path /5mlogq.avi
2024/11/27 12:38:12 Request: POST /bo4h0cvkr.asp from 182.100.136.6
2024/11/27 12:38:13 Headers: map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7] Accept-Encoding:[gzip, br] Accept-Language:[en-US,en;q=0.9] Cache-Control:[no-cache, no-store, must-revalidate] Cdn-Loop:[cloudflare; loops=1] Cf-Connecting-Ip:[182.100.136.6] Cf-Ipcountry:[CN] Cf-Ray:[8e93e3fea8ffeb1a-MAN] Cf-Visitor:[{"scheme":"https"}] Connection:[Keep-Alive] Content-Length:[0] Dnt:[1] Expires:[0] Pragma:[no-cache] Sec-Ch-Ua:["Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"] Sec-Ch-Ua-Mobile:[?0] Sec-Ch-Ua-Platform:["Windows"] Sec-Fetch-Dest:[document] Sec-Fetch-Mode:[navigate] Sec-Fetch-Site:[none] Sec-Fetch-User:[?1] Upgrade-Insecure-Requests:[1] User-Agent:[DarkFlare/1.0] X-Connection-Close:[true] X-Ephemeral:[76429d82e0dbe111016e88903e69334b] X-Forwarded-For:[182.100.136.6] X-Forwarded-Proto:[https]]
2024/11/27 12:39:13 Request: POST /6lfe1car.jpeg from 182.100.136.6
2024/11/27 12:39:13 Headers: map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7] Accept-Encoding:[gzip, br] Accept-Language:[en-US,en;q=0.9] Cache-Control:[no-cache, no-store, must-revalidate] Cdn-Loop:[cloudflare; loops=1] Cf-Connecting-Ip:[182.100.136.6] Cf-Ipcountry:[CN] Cf-Ray:[8e93e578da39b3d8-MAN] Cf-Visitor:[{"scheme":"https"}] Connection:[Keep-Alive] Content-Length:[3] Content-Type:[application/octet-stream] Dnt:[1] Expires:[0] Pragma:[no-cache] Sec-Ch-Ua:["Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"] Sec-Ch-Ua-Mobile:[?0] Sec-Ch-Ua-Platform:["Windows"] Sec-Fetch-Dest:[document] Sec-Fetch-Mode:[navigate] Sec-Fetch-Site:[none] Sec-Fetch-User:[?1] Upgrade-Insecure-Requests:[1] User-Agent:[DarkFlare/1.0] X-Ephemeral:[d44f91a7353c58afb586cd565efb85bf] X-Forwarded-For:[182.100.136.6] X-Forwarded-Proto:[https]]
2024/11/27 12:39:13 POST: Writing 3 bytes to connection for session d44f91a7
2024/11/27 12:39:13 Request: GET /zyyr5qaxx6y.jpg from 182.100.136.6
2024/11/27 12:39:13 Headers: map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7] Accept-Encoding:[gzip, br] Accept-Language:[en-US,en;q=0.9] Cache-Control:[no-cache, no-store, must-revalidate] Cdn-Loop:[cloudflare; loops=1] Cf-Connecting-Ip:[182.100.136.6] Cf-Ipcountry:[CN] Cf-Ray:[8e93e5784c85d184-LHR] Cf-Visitor:[{"scheme":"https"}] Connection:[Keep-Alive] Dnt:[1] Expires:[0] Pragma:[no-cache] Sec-Ch-Ua:["Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"] Sec-Ch-Ua-Mobile:[?0] Sec-Ch-Ua-Platform:["Windows"] Sec-Fetch-Dest:[document] Sec-Fetch-Mode:[navigate] Sec-Fetch-Site:[none] Sec-Fetch-User:[?1] Upgrade-Insecure-Requests:[1] User-Agent:[DarkFlare/1.0] X-Ephemeral:[d44f91a7353c58afb586cd565efb85bf] X-Forwarded-For:[182.100.136.6] X-Forwarded-Proto:[https]]
2024/11/27 12:39:13 GET: Read 68 bytes from connection for session d44f91a7
2024/11/27 12:39:13 Response: Sending 68 bytes (encoded: 136 bytes) for session d44f91a7 path /zyyr5qaxx6y.jpg
2024/11/27 12:39:13 Request: POST /vwrt6g.mp4 from 182.100.136.6
2024/11/27 12:39:13 Headers: map[Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7] Accept-Encoding:[gzip, br] Accept-Language:[en-US,en;q=0.9] Cache-Control:[no-cache, no-store, must-revalidate] Cdn-Loop:[cloudflare; loops=1] Cf-Connecting-Ip:[182.100.136.6] Cf-Ipcountry:[CN] Cf-Ray:[8e93e57ba88bd184-LHR] Cf-Visitor:[{"scheme":"https"}] Connection:[Keep-Alive] Content-Length:[0] Dnt:[1] Expires:[0] Pragma:[no-cache] Sec-Ch-Ua:["Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"] Sec-Ch-Ua-Mobile:[?0] Sec-Ch-Ua-Platform:["Windows"] Sec-Fetch-Dest:[document] Sec-Fetch-Mode:[navigate] Sec-Fetch-Site:[none] Sec-Fetch-User:[?1] Upgrade-Insecure-Requests:[1] User-Agent:[DarkFlare/1.0] X-Connection-Close:[true] X-Ephemeral:[d44f91a7353c58afb586cd565efb85bf] X-Forwarded-For:[182.100.136.6] X-Forwarded-Proto:[https]]
